# Generated by Django 3.1.3 on 2021-07-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('default', 'Choose Option'), ('digital', 'Digital Service'), ('govtscheme', 'Govt Service'), ('student', 'Student Service'), ('common', 'Common Service'), ('business', 'Business Service'), ('notification', 'Notification Service'), ('other', 'Other Service')], default='default', max_length=80),
        ),
    ]
